# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jsd <- function(text, group_list = as.character( c()), word_list = as.character( c()), group = "group", word = "word", n = "n") {
    .Call(`_jsd_jsd`, text, group_list, word_list, group, word, n)
}

